<?php

namespace Database\Factories;

use App\Models\Company\Company;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class CompanyFactory extends Factory
{
    protected $model = Company::class;

    public function definition()
    {
        $companyName = $this->faker->company;

        // Get a random user ID generated by the UserFactory
        $randomUserId = User::inRandomOrder()->value('id');

        return [
            'user_id' => $randomUserId, // Associate the company with a random user
            'name' => $companyName,
            'reference' => $this->faker->optional()->word,
            'personal_company' => $this->faker->boolean,
            'domaine_name' => Str::slug($companyName), // Generating slug from company name,
            'enabled' => 1,
            'email' => $this->faker->unique()->safeEmail,
            'phone' => $this->faker->unique()->phoneNumber,
            'phone_2' => $this->faker->unique()->phoneNumber,
            'address' => $this->faker->address,
            'city' => $this->faker->city,
            'country' => $this->faker->country,
            'domain' => $this->faker->randomElement(['clothing_store', 'electronics_store', 'supermarket', 'hyper_market', 'store_chain', 'drink_depot', 'cement_deposit', 'water_deposit', 'pharmacy', 'clinical', 'ngo', 'stationery_store', 'internet_cafe', 'cosmetic_store', 'beauty_salon', 'restaurant', 'bar', 'hotel', 'brand', 'other']),
            'size' => $this->faker->randomElement(['very_small','small', 'medium', 'large']),
            'primary_interest' => $this->faker->randomElement(['manage_my_business', 'digitize_my_business', 'for_school', 'dont_know']),
            'default_currency' => $this->faker->currencyCode,
        ];
    }
}
